export const enum ErrorCode {
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  IMAGE_PROCESSING_FAILED = 'IMAGE_PROCESSING_FAILED',
  VIDEO_PROCESSING_FAILED = 'VIDEO_PROCESSING_FAILED',
  MEDIA_STORAGE_FAILED = 'MEDIA_STORAGE_FAILED',
  CALENDAR_SYNC_FAILED = 'CALENDAR_SYNC_FAILED',
  CONTACTS_SYNC_FAILED = 'CONTACTS_SYNC_FAILED',
  UNSUPPORTED_SYNC_TYPE = 'UNSUPPORTED_SYNC_TYPE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  VALIDATION_ERROR = 'VALIDATION_ERROR'
}

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];