version: '3.8'
services:
  migration:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./apps/api:/app
      - /app/node_modules