version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      # Non-sensitive configuration only
      PORT: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    command: pnpm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    command: pnpm run dev:frontend

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

# Note: Sensitive data like API keys should be managed through Docker secrets
# in production. For development, use .env files that are git-ignored.