services:
  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:your_postgres_password@postgres:5432/postgres
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: your_postgres_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=https://diainolbnbrwkepnmrbq.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpYWlub2xibmJyd2tlcG5tcmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NzA3MDIsImV4cCI6MjA1MTQ0NjcwMn0.nJNaKrESub8emHud0WF0Sw4eOIMs5TRSjneZiTSjMiA
      - VITE_API_URL=http://backend:3001/api
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules